services:
  db:
    image: postgres:16
    container_name: sae5_6_InTheEnd
    command: postgres
    environment:
      POSTGRES_USER: InTheEnd_User
      POSTGRES_PASSWORD: InTheEnd_Password
      POSTGRES_DB: InTheEnd_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "25000:5432"
  redis:
    image: redis:trixie
    container_name: sae5_6_redis
    ports:
      - "6379:6379"
    
