services:
  db:
    image: postgres:16
    container_name: sae5_6_InTheEnd
    command: postgres
    environment:
      POSTGRES_USER: InTheEnd_User
      POSTGRES_PASSWORD: InTheEnd_Password
      POSTGRES_DB: InTheEnd_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # Auto création de la BDD, des tables et des triggers à partir du script SQL
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - ./trigger_bdd.sql:/docker-entrypoint-initdb.d/trigger_bdd.sql
    ports:
      - "25000:5432"